spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/defect_management
    username: root
    password: root



logging:
  level:
    com.back.assessment: debug
