spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  security:
    # 匿名接口，不需要认证授权
    patterns:
      - /login/**
      - /register/**
      - /search/**
      - /defect/**
      - /timelyRate/**

  datasource:
    url: jdbc:mysql://localhost:3306/defect_management
    username: root
    password: 123456




logging:
  level:
    com.back.assessment: debug
